### ISSUE TITLE
Add example for binary data type

### ISSUE THREAD

**Issue by chrbertsch** [modelica/Reference-FMUs#102]

**Comment by t-sommer** [comment]
The "Feedthrough" model [already has binary variables](https://github.com/modelica/Reference-FMUs/blob/master/Feedthrough/FMI3.xml#L39). What are you missing?

**Comment by chrbertsch** [comment]
> The "Feedthrough" model already has binary variables. What are you missing?

Ah, Thanks.  I just did not look deep enough into the existing reference FMUs.

With the hopefully growing numer of rerenfe FMUs, perhaps we should create an overview table, which feature is demonstrated / testd by which reference FMUs?
