### ISSUE TITLE
Add OSS licenses to reference FMUs

### ISSUE THREAD

**Issue by chrbertsch** [modelica/Reference-FMUs#105]
We should ship open source software licenses with the reference FMUs
Reason:  to give an example for the usage of the docuemtation/licecenses folder (see https://fmi-standard.org/docs/3.0-dev/#fmu-distribution), also in the light of https://github.com/modelica/fmi-cross-check/issues/114 to require from tools participating in the cross-check the necessary licesne information

Licesense files to be added: 
- BSD license of the reference FMUs https://github.com/modelica/Reference-FMUs/blob/master/LICENSE.txt 
- BSD  and CC-BY-SA License for the FMI Standard and header files CC-BY-SA
- (what else?)

**Comment by t-sommer** [comment]
The FMUs already contain a copy of the LICENSE.txt. The headers are not shipped in the FMUs.
