### ISSUE TITLE
Forked repository?

### ISSUE THREAD

**Issue by beutlich** [modelica/Reference-FMUs#106]
README.md states:

> The Reference FMUs are a fork of the Test FMUs by Dassault Systèmes, which are a fork of the FMU SDK by QTronic, both released under the 2-Clause BSD License.

This does not seem to be true as this repo is a real source repo and not a forked repo.

**Comment by pmai** [comment]
The term fork predates both git and the GitHub use of the word, in that it just means that a separate development stream is created (in whatever technical means was used to do so, i.e. grabbing a tarball, cloneing a repo, ...). So the sentence seems correct, regardless of whether GitHub "forking" was used to do the fork...

**Comment by beutlich** [comment]
Still confusing. Can you used "copied" or "cloned" repo instead to avoid the confusion. Thanks.

**Comment by pmai** [comment]
I'm sorry of the correct use of the word fork (see https://en.wikipedia.org/wiki/Fork_(software_development) ) confuses you, but incorrect use of copied or cloned (which is not necessarily what happened AFAIA), would unconfuse you. I have no chips in this game, so not my issue. But please get informed...

**Comment by beutlich** [comment]
OK, forked repo vs. forked project.
