### ISSUE TITLE
Remove attributes with default values from XMLs

### ISSUE THREAD

**Issue by t-sommer** [modelica/Reference-FMUs#18]
e.g. `numberOfEventIndicators="0"`

**Comment by andreas-junghanns** [comment]
The XSD also has some attributes that are setting the defaults, like maxOccurs="1".

**Comment by t-sommer** [comment]
> The XSD also has some attributes that are setting the defaults, like maxOccurs="1".

Please open an issue on fmi-standard. The XSDs are not part of the Reference FMUs.
