### ISSUE TITLE
Add ClockUpdateMode to MASK_ machinery

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/Reference-FMUs#196]

**Comment by andreas-junghanns** [comment]
Please check, if this needs to be fixed - maybe the few functions that are allowed to be called are already allowed in MASK_AnyState.

**Comment by andreas-junghanns** [comment]
Maybe the line:
`#define MASK_AnyState                     (~0)`
should list all FMI states explicitly.

**Comment by t-sommer** [comment]
Closing in favor of #98.
