### ISSUE TITLE
if earlyReturnAllowed  is false, fmi3DoStep should not return early.

### ISSUE THREAD

**Issue by masoud-najafi** [modelica/Reference-FMUs#197]
if earlyReturnAllowed is set false, then fmi3DoStep must not return early, regardless of the value of eventModeUsed.

**Comment by andreas-junghanns** [comment]
@masoud-najafi : Where did you see this issue? Which file?

**Comment by masoud-najafi** [comment]
At line 1462 of  fmi3Functions.c .
The code should also take into account the the attribute mightReturnEarlyFromDoStep.

**Comment by andreas-junghanns** [comment]
Can you create a PR? Or send me what the code should look like so I can create the PR?

**Comment by masoud-najafi** [comment]
[BouncingBall.zip](https://github.com/modelica/Reference-FMUs/files/7950403/BouncingBall.zip)

Hi,
Please check the attached zip file containing the modified files.
Thanks

**Comment by t-sommer** [comment]
Fixed with 5a4f95744af4125cbbcd3b14511d1920a44677f5.
