### ISSUE TITLE
MASK_AnyState too greedy

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/Reference-FMUs#199]
In fmi3Functions.c there is a macro: 
> #define MASK_AnyState                     (~0)

This would include modelError and modelFatal and especially modelFatal is likely wrong for most functions masks where MASK_AnyState is used, here is the definition of fmi3Fatal:

> fmi3Fatal
> The state of all instances of the model is irreparably corrupted. [For example, due to a runtime exception such as access violation or integer division by zero during the execution of an FMI function.] Function logMessage should be called by the FMU with further information before returning this status, respecting the current logging settings, if still possible. It is not allowed to call any other function for any instance of the FMU.

We should at least redefine MASK_AnyState.

The other issue is the state modelError: The models seem to set their state to modelError. What should that mean? Here is what we define with fmiError is returned:

>fmi3Error
> The call failed. The output argument values are undefined and the simulation cannot be continued. Function logMessage should be called by the FMU with further information before returning this status, respecting the current logging settings. If a function returns fmi3Error, it is possible to restore a previously retrieved FMU state by calling fmi3SetFMUState. Otherwise fmi3FreeInstance or fmi3Reset must be called. When detecting illegal arguments or a function call not allowed in the current state according to the respective state machine, the FMU must return fmi3Error. Other instances of this FMU are not affected by the error.

Are the models properly reporting errors and rejecting the correct functions then?

**Comment by t-sommer** [comment]
Closing in favor of #98.
