### ISSUE TITLE
Different Co-Simulation behavior in FMI 2.0 and FMI 3.0 FMUs

### ISSUE THREAD

**Issue by PTaeuberDS** [modelica/Reference-FMUs#203]
The Co-Simulation algorithm behaves differently for FMI 2.0 and FMI 3.0 FMUs of the same model.

In FMI 2.0 steps are performed
`while (S->time + FIXED_SOLVER_STEP < currentCommunicationPoint + communicationStepSize + epsilon(S->time))`
[fmi2Functions.c:641]

In FMI 3.0 the break criteria is:
`S->time + FIXED_SOLVER_STEP > currentCommunicationPoint + communicationStepSize + epsilon(S->time)`
[fmi3Functions.c:1450]

So, the behavior differs in the case:
`S->time + FIXED_SOLVER_STEP == currentCommunicationPoint + communicationStepSize + epsilon(S->time)`

With the FMI 3.0 behavior the obtained results are correct. So, I vote for using the FMI 3.0 behavior also for FMI 2.0.

This issue affects the results of Dahlquist.fmu, Stair.fmu and VanDerPol.fmu.

**Comment by pmai** [comment]
Can someone explain what is meant by "correct" here? Besides the fact that I have yet to see a sound numerical analysis of the epsilon tom-foolery (which seems misguided to say the least, based on IEEE semantics), but forcing the integrator beyond currentCommunicationPoint+communicationStepSize seems definetly wrong based on the FMI specifications... I.e. the FMI 2.0 behavior seems fundamentally correct.

**Comment by PTaeuberDS** [comment]
"Correct" means our tool obtains the same results as the references. Otherwise, at some times it happens due to precision errors that a DoStep returns without any calculation when that special case of equality happens. For instance, this happens for 8 communication points when simulating Dahlquist.fmu. Using the FMI 3.0 behavior always at least one solver step is performed and the results are equal to the references.

**Comment by t-sommer** [comment]
We could also require the `communicationStepSize` to be divisible (w/o remainder) by the fixed internal step size to avoid this problem. Accepting a `communicationStepSize < fixedInternalStepSize` makes not much sense anyways.

**Comment by PTaeuberDS** [comment]
That is not the cause of the problem. In the Dahlquist model `communicationStepSize` and `fixedInternalStepSize` both are 0.1 (and we do not change the default).

>but forcing the integrator beyond currentCommunicationPoint+communicationStepSize seems definetly wrong based on the FMI specifications...

I would not say that it would be "beyond" currentCommunicationPoint+communicationStepSize. It _is_ the communicationPoint just with an epsilon to compensate some precision errors.

At the first problematic step in Dahlquist the left handside
`S->time + 0.1`
is computed to: `4.2000000000000002`
with
`S->time = 4.1000000000000005`.
So, this would already be beyond the next communication point `t=4.2.` Thus communicationPoint `t=4.2`  gets the same results as communicationPoint `t=4.1`.
