### ISSUE TITLE
Feedthrough reference results are not valid for Co-Simulation

### ISSUE THREAD

**Issue by PTaeuberDS** [modelica/Reference-FMUs#205]
The results of Feedthrough.fmu are at least not valid for Co-Simulation.

- `real_discrete_out` always mirrors `real_discrete_in`, which is not the case in the results.
- `real_continuous_out` changes its value even when the variables it depends on are not changed according to the input file (0.5 < t < 1).
(`real_continuous_out`= `real_fixed_parameter`+ `real_tunable_parameter`+ `real_continuous_in`)
- The references show a direct feedthrough which is not possible with Co-Simulation DoSteps.
- `continuous_real_out` must be `real_continuous_out` and `discrete_real_out` must be `real_discrete_out` in the result file.

If the results are correct for the ME implementation, there should be at least another reference result for Co-Simulation.

**Comment by t-sommer** [comment]
Fixed with 0ee1e7df2af015ed1bab3459b1e60b29a9e354f3.
