### ISSUE TITLE
Error in Clocks/FMI3.xml

### ISSUE THREAD

**Issue by nickbattle** [modelica/Reference-FMUs#213]
Updating VDMCheck to the latest changes in the Standard, I get this error:
```
--------------- Clocks/FMI3.xml
Checking XML
1043: 2.4.4 Output clock "outClock" must not have a priority for Scheduled Execution at XML:14
Errors found.
```
Output clocks in SE must not have priorities; input clocks in SE must have them; no clocks have them unless SE is defined.

**Comment by t-sommer** [comment]
Closing as duplicate of #327.
