### ISSUE TITLE
Reference FMUs don't support static linking of two different FMUs

### ISSUE THREAD

**Issue by clagms** [modelica/Reference-FMUs#215]
Currently, we have a mechanism to enable static linking of different FMUs.
This is even used in the example that's listed in the standard: https://github.com/modelica/Reference-FMUs/blob/master/examples/co_simulation.c

However, the framework does not really support static linking because the prefixed functions call functions that are non prefixed, which means two fmi functions with two different prefixes will link to one common function.

Example:
1. Controller_fmi3SetFloat64  calls  fmi3SetFloat64 (in fmi3Functions.c) which calls setFloat64 (in modelcommon.c)
2. Plant_fmi3SetFloat64  calls  fmi3SetFloat64 (in fmi3Functions.c) which calls setFloat64 (in modelcommon.c)

In step 2, the Plant FMU returns error because the given value reference is not valid (because the code running belongs to the Controller FMU.

To solve this, I think we need to prefix all functions, to avoid name clashes.

**Comment by clagms** [comment]
I agree with @t-sommer , but don't the static linking examples, such as https://github.com/modelica/Reference-FMUs/blob/master/examples/import_static_library.c
and the use of FMI3_FUNCTION_PREFIX, seem to hint that this feature is supported by the code base?

**Comment by t-sommer** [comment]
The code will work, but you'll have to compile it separately, if you have more than one FMU with the same internal functions.
