### ISSUE TITLE
Inconsistent fmiVersions in Clocks example

### ISSUE THREAD

**Issue by MBlesken** [modelica/Reference-FMUs#226]
[Clocks/FMI3.xml](https://github.com/modelica/Reference-FMUs/blob/master/Clocks/FMI3.xml) states fmiVersion="3.0-beta.5" but the code interface is 3.0-beta.3. E.g. https://github.com/modelica/fmi-standard/pull/1585 has not be regarded. There may be more.

Also the [Clocks/buildDescription.xm](https://github.com/modelica/Reference-FMUs/blob/master/Clocks/buildDescription.xml) states fmiBuildDescription fmiVersion="3.0-alpha.2".

**Comment by t-sommer** [comment]
Can you please point out what aspect of `fmi3ClockUpdateCallback` has not been regarded?
