### ISSUE TITLE
CRT violation

### ISSUE THREAD

**Issue by y-schneidereit** [modelica/Reference-FMUs#227]
Hello,
I load my *.dll dynamically. `fmi2GetTypesPlatform` and `fmi2GetVersion` already worked.
`fmi2Instantiate` do not work. There is a CTR violation. I check the FMU with the FMU Check and there are no problems found.
With other FMU's I could call `fmi2Instantiate` and it works.
Do you know what could be the Problem? Here is a link to the repo: https://github.com/y-schneidereit/StandaloneFMU_PickAndPlace

Best regards,
Yannik

**Comment by t-sommer** [comment]
How is the above FMU related to the Reference FMUs?

**Comment by y-schneidereit** [comment]
Related to import_shared_library.c

**Comment by t-sommer** [comment]
The FMU fails to instantiate and gives the following error message:

```
Environment variable ALTAIRE_FMU_ROOT is not defined.
```

Seems like it needs an external tool or library. Please contact the tool vendor for more information.

**Comment by y-schneidereit** [comment]
Thank you very much, you helped me a lot!
Just one last question. How do you read this error? Is that possible with the logger function? Are there any examples how to use the logger funktion?

**Comment by t-sommer** [comment]
You have to set the [fmi2CallbackLogger](https://github.com/modelica/Reference-FMUs/blob/master/include/fmi2FunctionTypes.h#L119) to get the messages from the FMU.
