### ISSUE TITLE
Allow event handling w/o early return in FMI 3.0 CS

### ISSUE THREAD

**Issue by t-sommer** [modelica/Reference-FMUs#236]

**Comment by PTaeuberDS** [comment]
@t-sommer What are the plans here? Will you let the importer do the event handling if there is an event at a communication point and let the FMU do the event handling in all other cases, i.e. between communication points?
Is there any other way that would make sense?

**Comment by t-sommer** [comment]
I haven't really looked into this, yet. Please feel free to suggest a solution!

**Comment by PTaeuberDS** [comment]
@t-sommer You can assign this one to me, and also the two new ones I just created. Or you can provide me with the rights to do this by myself.

**Comment by t-sommer** [comment]
You can open a PR any time.
