### ISSUE TITLE
Error when simulating BouncingBall (FMI2.0, v0.0.16, Windows 64-bit)

### ISSUE THREAD

**Issue by ThummeTo** [modelica/Reference-FMUs#246]
Calling "BouncingBall" (FMI2.0, v0.0.16, Windows 64-bit, ZIP-Archive-Download) like in the following leads to an FMU-error:
`[Error][logStatusError][BouncingBall]: fmi2GetContinuousStates: Illegal call sequence.` for the call to `fmi2GetContinuousStates`.

The calling-sequence (pseudo-code) is:
```
comp = fmi2Instantiate(...)
fmi2SetupExperiment(comp, ...)
fmi2EnterInitializationMode(...)
fmi2ExitInitializationMode(...)
fmi2GetContinuousStates(...)
```

According to the pseudo code example of the [FMI-Spec](https://github.com/modelica/fmi-standard/releases/download/v2.0.3/FMI-Specification-2.0.3.pdf) (p. 91) as well as the calling-sequence-state-machine (p. 87) the following lines should work - and are implemented this way in [FMI.jl](https://github.com/ThummeTo/FMI.jl) (we have an issue facing this topic [here](https://github.com/ThummeTo/FMI.jl/issues/122)).

BTW: Calling `fmi2GetReal(comp, [Value References of Derivatives])` doesn't cause an error and works as expected.

Am I doing something wrong or is this an issue?

Best reagrds!

**Comment by t-sommer** [comment]
If I add the call to `fmi2GetContinuousStates()` to [simulate_fmi2_me.c](https://github.com/modelica/Reference-FMUs/blob/main/examples/simulate_fmi2_me.c) I get the following FMI log:

```
fmi2Instantiate(instanceName="instance1", fmuType=0, fmuGUID="{8c4e810f-3df3-4a00-8276-176fa3c9f003}", fmuResourceLocation="file:///Users/XXX/XXX/Reference-FMUs/build/temp/BouncingBall/resources/", functions={logger=0x0x100004d10, allocateMemory=0x0x7ff81ec82575, freeMemory=0x0x7ff81ec810ea, stepFinished=0x0x0, componentEnvironment=0x0x101441860}, visible=0, loggingOn=0) -> OK
fmi2SetupExperiment(toleranceDefined=0, tolerance=0, startTime=0, stopTimeDefined=1, stopTime=3) -> OK
fmi2EnterInitializationMode() -> OK
fmi2ExitInitializationMode() -> OK
fmi2GetContinuousStates(x={1, 0}, nx=2) -> OK
...
fmi2Terminate() -> OK
fmi2FreeInstance() -> OK
```

Please provide an executable example to reproduce the issue and reopen.

**Comment by ThummeTo** [comment]
Thanks for checking! I will try to narrow it down...

**Comment by ThummeTo** [comment]
Sorry for the wrong alert: I accidently instantiated the FMU in mode "1" (CS) instead of "0" (ME) and of course, `fmi2GetContinuousStates` is only available for ME 😅

So a general question: For the reference-FMUs, it is only possible to use them in the mode that was given during instantiation? I know e.g. Dymola-FMUs that are capable of using both CS as well as for ME for the same instance without errors.

**Comment by t-sommer** [comment]
This would not be a legal calling sequence.
