### ISSUE TITLE
v0.0.18/v0.0.19 do not contain regenerated documentation

### ISSUE THREAD

**Issue by beutlich** [modelica/Reference-FMUs#263]
* It is not clear if the readme.html files of the individual FMU dirs should be part of the repository since they are generated files.
* It is not clear who is responsible for regenerating the readme.html files.

**Comment by beutlich** [comment]
@t-sommer Just to let you know now that I have two more tiny PRs in progress.

**Comment by t-sommer** [comment]
Fixed with 0ee1e7df2af015ed1bab3459b1e60b29a9e354f3.
