### ISSUE TITLE
Incorrect BouncingBall_ref.csv

### ISSUE THREAD

**Issue by hyumo** [modelica/Reference-FMUs#279]
It seems that the position of the bouncing ball `h` is shifted by 1 time step. The velocity is correct tho.
![image](https://user-images.githubusercontent.com/6991617/188749852-e17666ed-33d2-4d06-8c7f-c27e77b9a650.png)

Here's a simple experiment created from Dymola which produces the correct `h` trace.

![image](https://user-images.githubusercontent.com/6991617/188749614-8066a6e9-cb79-45ce-a5df-ddde9b68463a.png)

**Comment by hyumo** [comment]
And btw, there's analytical solution to this test before the ball hitting the ground: $h_{0} + \frac{1}{2}gt^{2}$

**Comment by StephenSmith25** [comment]
I noticed this as well. I think this is just a result of using a forward Euler scheme. At the first timestep, $n=1$,  we are using the initial conditions to find $h(1)$. 

$( h(1) - h(0) ) / \Delta T = v(0) = 0$

Given $h(0) = 1$, $h(1)$ must also be 1. This is just the approximation error of the forward difference scheme, it will decrease with timestep size.

**Comment by t-sommer** [comment]
Fixed with 0ee1e7df2af015ed1bab3459b1e60b29a9e354f3.

**Comment by hyumo** [comment]
I found that reference csv files are deleted, I guess they will be provided in release artifacts in the future, is that correct?

**Comment by t-sommer** [comment]
The distribution now also contains a reference implementation for FMU import (`fmusim`) the lets you generate reference results for any FMU. To get the output for the default experiment you can run:

```
fmusim --output-file Model_ref.csv Model.fmu
```

Please open a new issue if you find any problems or inconsistencies.
