### ISSUE TITLE
Serialization and deserialization of the FMU state

### ISSUE THREAD

**Issue by StephenSmith25** [modelica/Reference-FMUs#323]
Hey, sorry if this is a silly comment, but I'm currently trying to look into serialization and deserialization. I was looking here for just some examples of this functionality. Observing the current serialization and deseriazlisation functions, I notice it makes use of `memcpy`, which is okay for the POD structure and most its data types, but it doesn't handle the pointer types, e.g,

```
typedef struct {
    .....
    const char *resourceLocation;
    .....
} ModelInstance
```

`memcpy` here will just copy the pointer address, rather than the data, which will not remain valid if I was going to launch the FMU again. Unless I'm mistaken, as I'm fairly new to the business of serialization!

Is this just an accepted limitation of the tutorials, which aren't necessarily meant to be fully complete examples? If so, is there any other resources for example FMUs that use this functionality to save the state to file?

**Comment by t-sommer** [comment]
The `resourceLocation` is set when the FMU instance is created, so it's already present when a (de-serialized) state is set.
