### ISSUE TITLE
Issues found in FMI2 configuration of Reference FMUs

### ISSUE THREAD

**Issue by nickbattle** [modelica/Reference-FMUs#36]
A couple of errors are raised by the formal checking of the FMI2 Reference FMUs:
```
-------------------- Resource/FMI2.xml
2.2.7 Variable "y" initial/variability/start <calculated>/<continuous>/0 invalid at line 29
2.2.8 InitialUnknowns must include: {1}
Errors found.

A calculated value cannot have a start attribute.
The initial unknowns should include 1 because it is an output variable that is calculated, by default.

-------------------- Stair/FMI2.xml
2.2.7 Continuous variable must be Real at line 29
Errors found.

The value is declared as an Integer.
```

**Comment by t-sommer** [comment]
@nickbattle, can you propose a fix?

**Comment by nickbattle** [comment]
@t-sommer I can propose arbitrary changes that will pass validation, but these are *reference* FMUs which presumably are intended to work in a particular way, so I think the FMU authors really ought to decide what the correct settings should be.

In the Resource/FMI2.xml case, the variable "y" is invalid because its "initial" clause defaults to "calculated" and you cannot have a "start" value if a variable is calculated. So one solution would be to remove the start clause. Or you could define a different "initial" setting. I don't know the intent of the model, so I can't guess which is appropriate.

Fixing the "InitialUnknowns" just means adding a InitialUnknowns section to the ModelStructure that is the same as the Outputs section. Though if you change the initial value of "y", you don't have to include it in the InitialUnknowns (only "approx" or "calculated" outputs are needed in InitialUnknowns).

The fix for Stair/FMI2.xml is easier. From the name "counter", I *assume* it is discrete rather than continuous, and therefore should have a variability of "discrete" rather than the default, which is "continuous".

If someone can indicate which changes are appropriate, I can re-validate them.

**Comment by t-sommer** [comment]
> therefore should have a variability of "discrete" rather than the default, which is "continuous"

The FMI 2.0.1 Spec is ambiguous here:

on page 48 it says: 

>  (a) Only a variable of type = “Real” can be “continuous”.  [...] (b) The default is “continuous”.

IMHO the (b) takes precedence over (a).

**Comment by nickbattle** [comment]
Yes, I agree, otherwise we do not know the variability of non-Reals without explicit variabilities. The formal model always regards ScalarVariables with a missing variability as "continuous". In the case of your PR, that causes another error, because the type is now "Integer" which cannot be "continuous". It needs a variability clause to say the variable is "discrete".

As you say, this is clarified in FMI3 and the formal model therefore implements this and your PR changes for the FMI3.xml are accepted (though the InitialUnknowns issue remains in both).
