### ISSUE TITLE
building fmusim fails due to missing file

### ISSUE THREAD

**Issue by albert-mathews** [modelica/Reference-FMUs#369]
Hello, 

I wanted to build fmusin from source, so i did the following the steps:

1. cloned repo to /some_dir/
2. cd to /some_dir/Reference-FMUs/fmusim/
3. create dir called build_dir
4. cd into /some_dir/Reference-FMUs/fmusim/build_dir
5. `cmake ..`

and this is the error i get.

-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
CMake Error at CMakeLists.txt:74 (add_executable):
  Cannot find source file:

    /some_dir/Reference-FMUs/fmusim/ThirdParty/zlib-1.2.13/contrib/minizip/ioapi.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc

CMake Error at CMakeLists.txt:74 (add_executable):
  No SOURCES given to target: fmusim

CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by t-sommer** [comment]
Did you clone the repo with `--recurse-submodules`?

**Comment by albert-mathews** [comment]
hello @t-sommer , and thank you for your help. (note i'm really dumb with linux and using WSL2). 

i did try `--recurse-submodules` in a subsequent attempt, but got the same problem (the submodule dirs i expected to see were not there, i have retried this, and pasted the result below in case i'm doing something wrong). 
result of clone with recurse-submodule:
![image](https://github.com/modelica/Reference-FMUs/assets/80334291/9efa5f96-3771-43d9-a10d-eb72bcc9e274)

i assume that `fmusim/ThirdParty` would have dirs for `zlib` and `libxml`. 



in yet another subsequent attempt, i created the submodule for `zlib` manually in `Reference-FMUs/fmusim/ThirdParty/zlib-1.2.13`, and that solved the problem outlined in this issue. but this same approach did not work for `libxml` despite several attempts. i suspect i would have encountered this same problem with `cvode`, but in that case I was lazy and just commented out all of `FMICVode.c` since i dont really need the sophisticated solver for my purposes, which is just learning how to generate FMUs from a modeling tool. 

in my latest attempt, i'm using the `build_<pkg>.py` files in `Reference-FMUs/ThirdParty` which seem to do the right thing, except that `zlib` and `libxml` end up in `Reference-FMUs/ThirdParty` instead of `Reference-FMUs/fmusim/ThirdParty`. the screenshot below shows the outcome after having run those scripts in a fresh clone.
![image](https://github.com/modelica/Reference-FMUs/assets/80334291/f94e2fff-ac4c-42ca-8e3b-d0eb06bec28d)

as you can see, although the dirs were created, they aren't found by cmake from `fmusim/build`;
![image](https://github.com/modelica/Reference-FMUs/assets/80334291/a5f0eac1-3a61-4787-b19c-a949a39e66f4)


so did this:
![image](https://github.com/modelica/Reference-FMUs/assets/80334291/c2a61db8-ead2-4797-964c-0842507b49f2)

and now it seems the build works, i.e. I am able to `fmusim/build$ cmake ..` and then `fmusim/build$ make`, and then running the Bouncingball.fmu example works:
![image](https://github.com/modelica/Reference-FMUs/assets/80334291/bdc833b4-4ec5-4e77-8fb6-7ee0a27ea889)


so i think maybe I have simplified my question. why does the `ThirdParty` dir appear in `/Reference-FMUs` instead of `/Reference-FMUs/fmusim` ? for your gitworkflow to work, is it in `build.py` around line 70 that this is handled?

**Comment by t-sommer** [comment]
The easiest way to build the dependencies for `fmusim` is to run the build scripts that are used in CI (see https://github.com/modelica/Reference-FMUs/blob/main/.github/workflows/build.yml#L39).

**Comment by chintanp** [comment]
Anyone trying to find directions for building `fmusim`, since the link points to somewhere less relevant now:

1. Install Python. 
2. `pip install fmpy requests`
3. `python build/build_cvode.py ${{ matrix.name }}` where ${{matrix.name}} can be replaced by the platform for build.
4.  `python build/build_libxml2.py ${{ matrix.name }}`
5.  `python build/build_zlib.py ${{ matrix.name }}`
6. `python build/build.py ${{ matrix.name }}`

And this should build `fmusim` as well as the Reference FMUs. For me in Windows, I found the `fmusim` in `.\build\fmus\fmusim-x86_64-windows` and was able to test the `fmusim` by running `fmusim --log-fmi-calls ..\2.0\BouncingBall.fmu` which should print several OKs and finally a results.csv in the directory.
