### ISSUE TITLE
building FMU .so file does not seem to work

### ISSUE THREAD

**Issue by albert-mathews** [modelica/Reference-FMUs#370]
I wanted to learn how to make an FMU .so file, so I did the following steps.

1. closed the repo to /some_dir/
2. unzip BouncingBall.fmu to /some_dir/bb_unzip/
3. cd to /some_dir/bb_unzip/sources/
4. `gcc -I. -c all.c -shared -o ../binaries/linux64/BouncingBall.so` which I assumed would remake the .so
5. rezip with remade .so file to BouncingBall2.fmu
6. `fmusim BouncingBall2.fmu`

but this results in a segmentation fault.
`Program received signal SIGSEGV, Segmentation fault.`
`0x000055555556e6e3 in FMI2Instantiate ()`

I was able to make all FMUs successfully using `/some_dir/CMakeLists.txt` and browse the files that come from that, but I guess I was hoping there was a more straight forward way to build a .so file from source. 

Any suggestions?

**Comment by t-sommer** [comment]
Please follow [the contribution guide](https://github.com/modelica/Reference-FMUs/blob/main/CONTRIBUTING.md) and ask this question on StackOverflow.
