### ISSUE TITLE
Please provide win32 build of fmusim

### ISSUE THREAD

**Issue by fajansen** [modelica/Reference-FMUs#386]
Please also provide a win32 build of fmusim as a lean way to simulate 32bit windows FMUs.

**Comment by t-sommer** [comment]
Would it be acceptable to modify the build scripts, so you can build the 32-bit Windows binaries yourself.

**Comment by t-sommer** [comment]
Solved with fa15f2b8eaebd7636d72da94aca5f747fb04fd6d.
