### ISSUE TITLE
Add support for array inputs

### ISSUE THREAD

**Issue by PRAVEENFrmBOSCH** [modelica/Reference-FMUs#391]
I couldn't able to test the LinearTransform.fmu , i have tried using below csv.
[input1.csv](https://github.com/modelica/Reference-FMUs/files/12426951/input1.csv)

Getting Error in below Code :
https://github.com/modelica/Reference-FMUs/blob/main/LinearTransform/model.c : setFloat64()  Line no : 84

nValues is 1 
m * n    is 4

**Comment by PRAVEENFrmBOSCH** [comment]
https://github.com/modelica/Reference-FMUs/blob/main/fmusim/fmusim_input.c : line no 243 
always sending nValues=1 

But in https://github.com/modelica/Reference-FMUs/blob/main/LinearTransform/model.c : setFloat64() Line no : 84
Throwing error when m*n > nValues which is 4 > 1

**Comment by t-sommer** [comment]
Solved with #395. See [resources/LinearTransform_in.csv](https://github.com/modelica/Reference-FMUs/blob/main/tests/resources/LinearTransform_in.csv) for an example of an input CSV with arrays.
