### ISSUE TITLE
Create a minimal example with partial derivatives

### ISSUE THREAD

**Issue by chrbertsch** [modelica/Reference-FMUs#4]
moved from https://github.com/CATIA-Systems/Test-FMUs/issues/14

One could e.g. use the LinearTransform example. There trivially the Jacobian is just the Matrix A; so one can easily provide dirictionalderivatives by multiplying with A.

And I would like to extend this for the adjoint derivatives modelica/fmi-standard#722.

**Comment by t-sommer** [comment]
> One could e.g. use the LinearTransform example.

The VanDerPol model might be the better model to demonstrate this feature. It already implements [getPartialDerivative()](https://github.com/modelica/Reference-FMUs/blob/master/VanDerPol/model.c#L84).

**Comment by t-sommer** [comment]
Doesn't the [jacobian.c](https://github.com/modelica/Reference-FMUs/blob/master/examples/jacobian.c) example already demonstrate the use of partial derivatives?

**Comment by chrbertsch** [comment]
> Doesn't the [jacobian.c](https://github.com/modelica/Reference-FMUs/blob/master/examples/jacobian.c) example already demonstrate the use of partial derivatives?

Yes it does
