### ISSUE TITLE
fmi3DoStep returns eventHandlingNeeded=true even if the event was already handled by the FMU

### ISSUE THREAD

**Issue by PTaeuberDS** [modelica/Reference-FMUs#420]
According to the standard eventHandlingNeeded=true is returned to signal that the importer has to do the event handling and shall enter event mode.
Therefore, if the event is already handled and time has progressed further, eventHandlingNeeded should not be set to true.

**Comment by t-sommer** [comment]
Fixed with 5a4f95744af4125cbbcd3b14511d1920a44677f5.
