### ISSUE TITLE
Memory leak in example FMUs

### ISSUE THREAD

**Issue by jessebarrosilia** [modelica/Reference-FMUs#427]
In our sanity checks, we identified a memory leak inside of the example FMUs being loaded dynamically.
By further investigation, we reached the conclusion that Modellica's FMUs code ModelInstance owned a char* resource location that was allocated in createModelInstance but never deallocated. Therefore, it was leaking memory.

In the following images, we see that when we compile using flag ` -fsanitize=address` we identify these leaks in multiple example fmus.

![pathless_modelica_leak_bouncingball](https://github.com/modelica/Reference-FMUs/assets/149105301/62a0cb77-b152-4223-8c38-130e2d3b4208)

![pathless_modelica_leak_resource](https://github.com/modelica/Reference-FMUs/assets/149105301/80cd85cb-53aa-4958-b92c-a316f17acaab)

![pathless_modelica_leak_dahlquist](https://github.com/modelica/Reference-FMUs/assets/149105301/18b65f63-8b65-4c17-a69c-7b094b931406)

**Comment by jessebarrosilia** [comment]
@t-sommer  and @PTaeuberDS 
I am writing to you because you have been reviewing PRs lately.

I hope that my explanations for the bug and its fix are clear. 
I have been using the example fmus for a while now 
and this bug was constantly forcing our checks to suppress memory leaks.
So I am creating this PR with a fix that can be used by all the community.

**Comment by t-sommer** [comment]
Fixed with 0f285b6ed4a09898f0a6e2f099b478be03a073e8.
