### ISSUE TITLE
issues with fmi2.0-CS FMUs in 0.0.28 build

### ISSUE THREAD

**Issue by masoud-najafi** [modelica/Reference-FMUs#457]
The CS FMUs in particular bouncingball.fmu and Vanderpol do not work for cosimulation-fmi2.0.
It seems that the call to the configurate(comp); is missing to set comp->nx and comp->nz.

**Comment by t-sommer** [comment]
Can you provide steps to reproduce the problem?

**Comment by masoud-najafi** [comment]
Just check these FMUs wit FMUComplienceChecker. The results are constant values. here is the command line.
..\fmuCheck.win64.exe -l 5 -k cs E:\FMI\Git_Reference-FMUs\Reference-FMUs-0.0.28\2.0\BouncingBall.fmu

**Comment by t-sommer** [comment]
I can simulate the FMU without problems:

```
C:\Users\XXX\Downloads>FMUChecker-2.0.4-win64\fmuCheck.win64.exe -l 5 -k cs Reference-FMUs-0.0.28\2.0\BouncingBall.fmu
...
[INFO][FMUCHK] Simulation finished successfully at time 3
[VERBOSE][FMILIB] Releasing allocated library resources
[VERBOSE][FMILIB] Releasing FMU CAPI interface
[VERBOSE][FMICAPI] Successfully unloaded FMU binary
...
FMU check summary:
FMU reported:
        0 warning(s) and error(s)
Checker reported:
        0 Warning(s)
        0 Error(s)
```

**Comment by chrbertsch** [comment]
Hm, but I can confirm that simulating this FMU with fmpy gives constant outputs for CS, while ME looks good ...

**Comment by masoud-najafi** [comment]
Yes, the simulation with ME is fine and gives the expected results, but CS gives constant values. Adding configurate(comp);  in the instantiate() of CS, fixes the issue.
