### ISSUE TITLE
fmi3GetInt32 fails in reading the input in Clocks.fmu

### ISSUE THREAD

**Issue by masoud-najafi** [modelica/Reference-FMUs#460]
Hi,
The FMU raises this error : 
"Get Int32 is not allowed for value reference 2006", 
when fmi3GetInt32 is called to retrieve the input value.
Thanks,
Masoud

**Comment by MBlesken** [comment]
Hello @masoud-najafi, @t-sommer's PR will fix this issue. Let's merge it. (I was a bit surprised that a _get_ can be executed on an input. Now I learned.)
