### ISSUE TITLE
System.AccessViolationException: 'Attempted to read or write protected memory.

### ISSUE THREAD

**Issue by GMTulasikumar** [modelica/Reference-FMUs#462]
Hi, 

I am getting above issue (System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.') while using FMI 2.0.
This is issue is reproduceable only with respect to particular FMU file.
Even I tried to debug above issue using FMU checker and log files . Please find the below log info

[INFO][FMUCHK] Printing output file header
[INFO][FMUCHK] Opening input file TESTSAMPLE.csv
[INFO][FMUCHK] Detected separator character in input file: ,
[INFO][FMUCHK] Model identifier for CoSimulation: TESTSAMPLE
[INFO][FMILIB] Loading 'win32' binary with 'default' platform types
[VERBOSE][FMICAPI] Loaded FMU binary from C:\Users\XYZ\AppData\Local\Temp\fmucktmpa35292\binaries\win32\TESTSAMPLE.dll
[VERBOSE][FMICAPI] Loading functions for the co-simulation interface
[VERBOSE][FMILIB] Successfully loaded all the interface functions
[VERBOSE][FMICAPI] Calling fmi2GetVersion
[VERBOSE][fmi2GetVersion] [FMU status:OK] version = 2.0
[INFO][FMUCHK] Version returned from CS FMU:   2.0
[VERBOSE][FMICAPI] Calling fmi2GetModelTypesPlatform
[VERBOSE][fmi2GetModelTypesPlatform] [FMU status:OK] platfrom = default
[VERBOSE][FMICAPI] Calling fmi2Instantiate
[VERBOSE][FMUCHK] allocateMemory( 1, 128) called. Returning pointer: 015AA310
[VERBOSE][FMUCHK] allocateMemory( 2, 8) called. Returning pointer: 0159E340
[VERBOSE][FMUCHK] allocateMemory( 0, 4) called. Returning pointer: 015AD9E8
[VERBOSE][FMUCHK] allocateMemory( 0, 4) called. Returning pointer: 015ADB58
[VERBOSE][FMUCHK] allocateMemory( 0, 4) called. Returning pointer: 015ADBA8
[VERBOSE][FMUCHK] allocateMemory( 0, 4) called. Returning pointer: 015ADA78
[VERBOSE][FMUCHK] allocateMemory( 16, 1) called. Returning pointer: 0159E0E8
[VERBOSE][FMUCHK] allocateMemory( 39, 1) called. Returning pointer: 0156EF18
	[FMU][logFmiCall][FMU status:OK] fmi2Instantiate: GUID={GUid I will get it here}
[VERBOSE][fmi2Instantiate] [FMU status:OK] instanceName = Test FMI 2.0 CS, fmuType = 1, fmuGUID = {GUid I will get it here}, fmuResourceLocation = file:///C:/Users/AppData/Local/Temp/fmucktmpa35292/resources, visible = 0, loggingOn = 1 
[VERBOSE][FMICAPI] Calling fmi2SetReal
	[FMU][logFmiCall][FMU status:OK] fmi2SetReal: nvr = 1
	[FMU][logFmiCall][FMU status:OK] fmi2SetReal: Temp_GT_in = 0
[VERBOSE][Calling fmi2SetReal] [FMU status:OK] 
[VERBOSE][FMICAPI] Calling fmi2SetupExperiment
	[FMU][logFmiCall][FMU status:OK] fmi2SetupExperiment: toleranceDefined=0 tolerance=0.0001
[VERBOSE][fmi2SetupExperiment] [FMU status:Error] tolerance_defined = 0, tolerance = 0.000100, start_time = 0.000000, stop_time_defined = 0, stop_time = 0.000000
[FATAL][FMUCHK] Failed to initialize FMU for simulation (FMU status: Error)
[FATAL][FMUCHK] Simulation loop terminated at time 0 since FMU returned status: Error
	[FMU][logError][FMU status:Error] fmi2Terminate: Illegal call sequence.
[VERBOSE][fmi2Terminate] [FMU status:Error] 
[ERROR][FMUCHK] fmiTerminateSlave returned status: Error
[VERBOSE][FMICAPI] Calling fmi2FreeInstance
	[FMU][logFmiCall][FMU status:OK] fmi2FreeInstance
[VERBOSE][FMUCHK] freeMemory(0159E340) called
[VERBOSE][FMUCHK] freeMemory(015AD9E8) called
[VERBOSE][FMUCHK] freeMemory(015ADB58) called
[VERBOSE][FMUCHK] freeMemory(015ADBA8) called
[VERBOSE][FMUCHK] freeMemory(015ADA78) called
[VERBOSE][FMUCHK] freeMemory(0159E0E8) called
[VERBOSE][FMUCHK] freeMemory(0156EF18) called
[VERBOSE][FMUCHK] freeMemory(015AA310) called
[VERBOSE][FMILIB] Releasing allocated library resources
[VERBOSE][FMILIB] Releasing FMU CAPI interface
[VERBOSE][FMICAPI] Successfully unloaded FMU binary
[VERBOSE][JMPRT] Removing C:\Users\AppData\Local\Temp\fmucktmpa35292
FMU check summary:
FMU reported:
	1 warning(s) and error(s)
Checker reported:
	1 Warning(s)
	3 Error(s)
	2 Fatal error(s) occurred during processing

**Comment by t-sommer** [comment]
How is this problem related to the Reference FMUs?

**Comment by GMTulasikumar** [comment]
Yes I agree, Do you have any idea about this problem?

**Comment by t-sommer** [comment]
Please contact the vendor of the tool that was used to export the FMU.
