### ISSUE TITLE
Clocks.fmu: clcoks attribute of the totalInClockTicks variable

### ISSUE THREAD

**Issue by masoud-najafi** [modelica/Reference-FMUs#465]
In the XML of Clocks.fmu, totalInClockTicks is activated by clocks 1001 and 1003.
  <Int32 name="totalInClockTicks" valueReference="2004" causality="output" clocks="1001 1003"/>

But in the C code, this variable is read and increamented inside activateModelPartition2(). Is this allowed in SE?

**Comment by MBlesken** [comment]
@masoud-najafi yes it should be 

`<ModelVariables>...<Int32 name="totalInClockTicks" valueReference="2004" causality="output" clocks="1001 1002 1003"/> ...</ModelVariables>`
