### ISSUE TITLE
Getstring in model.h

### ISSUE THREAD

**Issue by mathcodemaster** [modelica/Reference-FMUs#473]
Hello, 
i am a big fan of the reference fmus,

this might be a stupid question,
but in model.h the getstring function is defined as
Status getString  (ModelInstance* comp, ValueReference vr, const char* value[], size_t *index);

is the const here at the correct spot? doesnt that make the value a pointer to const arrays? and the puropse is to write into the arrays right?

best regards

Franz

**Comment by t-sommer** [comment]
`const char* value[]` is an array of `const char*` that can be changed by the FMU.
