### ISSUE TITLE
Support tunable parameters

### ISSUE THREAD

**Issue by LxZ-1002** [modelica/Reference-FMUs#490]
Support to tune FMU parameters (in modelDescription.xml variability="tunable") during the sim

**Comment by t-sommer** [comment]
You can set tunable parameters via the input file, just like discrete inputs. E.g.

Feedthrough_in.csv:

```
time,Float64_tunable_parameter
0,1
1,2
2,3
```

```
fmusim --input-file Feedthrough_in.csv Feedthrough.fmu
```
