### ISSUE TITLE
SetFloat64 on x in state space FMU ME

### ISSUE THREAD

**Issue by KarlWernersson** [modelica/Reference-FMUs#508]
The FMU don't allow setting state vector x.
This should be allowed in Model Exchange

**Comment by t-sommer** [comment]
Can you provide steps to reproduce the problem?

**Comment by KarlWernersson** [comment]
call setFloat64 with value reference 11 in mode exchange, the code does not allow that value reference

**Comment by t-sommer** [comment]
In [Intialization Mode](https://fmi-standard.org/docs/3.0.1/#InitializationMode):

> Function [fmi3Set{VariableType}](https://fmi-standard.org/docs/3.0.1/#get-and-set-variable-values)
This function can be called for variables with [variability](https://fmi-standard.org/docs/3.0.1/#variability) ≠ [constant](https://fmi-standard.org/docs/3.0.1/#constant) and with [initial](https://fmi-standard.org/docs/3.0.1/#initial) = [exact](https://fmi-standard.org/docs/3.0.1/#exact). [[Inputs](https://fmi-standard.org/docs/3.0.1/#input) u, [parameters](https://fmi-standard.org/docs/3.0.1/#parameter) p and continuous-time [states](https://fmi-standard.org/docs/3.0.1/#state) xc,initial=exact are included here.]

The variable `x` (with value reference `11`) has `initial = "calculated"`, so I should it be settable?

**Comment by KarlWernersson** [comment]
no but its is a state so it should be settable in continuous time mode and event mode. In initialization mode its not as the initial values is internally computed.
