### ISSUE TITLE
Building FMUs/fmusim on aarch64-darwin

### ISSUE THREAD

**Issue by Maplesoft-fmigroup** [modelica/Reference-FMUs#514]
@t-sommer  I was able to build 'fmusim' and reference FMUs on ARM M2 Mac. When running build.py I had to fix the following:
`Reference-FMUs/src/fmi3Functions.c:241:27: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
const char* fmi3GetVersion() {`                                       
by changing it to `const char* fmi3GetVersion(void)`.
There were also a bunch of warnings. Let me know if you want the list.

**Comment by t-sommer** [comment]
Yes, please!

**Comment by Maplesoft-fmigroup** [comment]
[Buildfmusim.txt](https://github.com/user-attachments/files/15827441/Buildfmusim.txt)
