### ISSUE TITLE
Loading float numbers from external data CSV file fails.

### ISSUE THREAD

**Issue by malinb73** [modelica/Reference-FMUs#534]
--- Context ---
Built fmusim for Windows:
	Platform: x86_64-windows
	CMake Generator: Visual Studio 16 2019
	Build type: Debug

Git commit checked:
	Revision: 6d3a981d0be4db65be2ae5e8a58aaad724e32007
	Author: Torsten Sommer <torsten.sommer@3ds.com>
	Date: 7/5/2024 11:19:21 AM
	Message: Fix variable index in fmi3{Get|Set}Binary() (#531)

--- Description ---
The error happens when importing external data from a CSV file and amongst other different inputs there are also inputs having float types.

Example:
**time,s8_in,s16_in,array1D_in,float32_in
0,1,2,3 4 5,12.34**

The error happens randomly.
The error message is: "Failed to reallocate memory."
The error occurs in **_fmusim/FMIStaticInput.c_** in function:
`FMIStatus FMIApplyInput(FMIInstance* instance, const FMIStaticInput* input, double time, bool discrete, bool continuous, bool afterEvent)`
at line 276:
`CALL(FMIRealloc((void**)&input->buffer, requiredBufferSize));`
The reason is requiredBufferSize variable has sometimes a very huge value due to some wrong memory read which is based on row variable.
This row variable is calculated in the while block from lines 255, see: "**_while (row < input->nRows - 2) {...._**"
Changing the while condition to "**_while (row < input->nRows - 1)_**" seems to solve the problem.
Can you check please?

**Comment by t-sommer** [comment]
Can you reproduce the problem if you use an input file with at least 3 rows? 

E.g.

```
time,s8_in,s16_in,array1D_in,float32_in
0,1,2,3 4 5,12.34
1,1,2,3 4 5,12.34
2,1,2,3 4 5,12.34
```

**Comment by malinb73** [comment]
Hi Sommer,

I made again 3 tests and this is the status:
01.  tested with 0.0.31
       - for 1 line fails
       - for more that 1 line ok

02.  tested with commit Revision: 6d3a981
       - for 1 line fails
       - for more that 1 line ok

03.  tested with my fix
       - for 1 line ok
       - for more that 1 line ok

I am not saying that I understood completely the code of **_FMIApplyInput()_** function from **_FMIStaticInput.c_** but the fix suggested is based on next fact:
I compared the code which fails from:
`if (continuous && variable->variability == FMIContinuous)`
with the code which works fine from:
`else if (discrete && (variable->variability == FMIDiscrete || variable->variability == FMITunable))`
and beside the specific code which handles _FMIFloat32Type_ and _FMIFloat64Type_ the notable difference is 
`while (row < input->nRows - 2)`
VS.
`while (row < input->nRows - 1)`
Playing around with this condition and changing it to "_row < input->nRows - 1_" proved that worked fine also for floats (variability = FMIContinuous)

**Comment by malinb73** [comment]
Hi Sommer,
I can confirm that now it works as expected.
Can you tell me when is scheduled the next release having this fix?
Thank you,
Bogdan

**Comment by stanislav-git84** [comment]
Hi @t-sommer 
thank you for resolving this very quickly.
May I ask by when we can expect a new Release containing this change?
Thank you, Stanislav

**Comment by t-sommer** [comment]
You can download the binaries directly from the CI: https://github.com/modelica/Reference-FMUs/actions/runs/10073277513/artifacts/1734054905
