### ISSUE TITLE
CMake of Reference FMU'S

### ISSUE THREAD

**Issue by sergiochavezlazo96** [modelica/Reference-FMUs#542]
Hello,
I am trying to build my own FMUs and I am trying to find out references. I noticed that the 2.0 references FMU's (e.g. BouncingBall) does not contain a CMAKE file. Is there any chance to know about how did you compile those FMU's?
Thank you!

**Comment by t-sommer** [comment]
Have you tried to follow the [Build the FMUs](https://github.com/modelica/reference-fmus?tab=readme-ov-file#build-the-fmus) section in the README?
