### ISSUE TITLE
Separation of simulation results and errors

### ISSUE THREAD

**Issue by stanislav-git84** [modelica/Reference-FMUs#563]
In [FMI Compliance Checker](https://github.com/modelica-tools/FMUComplianceChecker), the separation of "Error logs" (_-e_) from Simulation Results (_-o_) was very handy. Also the possibility to select the "verbosity" of logging (I believe logging of errors) via (_-l_) was super useful.

It seems the warning/error logging is now also being added to fmusim [#559](https://github.com/modelica/Reference-FMUs/pull/559) which I am very happy about.
Could you please also add an equivalent of the _-l_ option for setting the "verbosity"?

**Comment by alexad19** [comment]
Hi @t-sommer, 

I am wondering if you could also help us with the -e option (the redirecting of the fmi errors/warnings to a file). I believe this could be of great help for other developers as well.

Thank you!

**Comment by t-sommer** [comment]
> I am wondering if you could also help us with the -e option (the redirecting of the fmi errors/warnings to a file).

Isn't this solved with #565?

**Comment by alexad19** [comment]
Not really. 
Resulting log.txt file with the running of the
`fmusim.exe --log-fmi-calls --logging-on --log-level ok --fmi-log-file log.txt SimpleExample.fmu`

![image](https://github.com/user-attachments/assets/de10e68c-96e7-446e-87d6-150992d326bc)

Resulting log.txt file with the running of the
`fmusim.exe --log-fmi-calls --logging-on --log-level warning --fmi-log-file log.txt SimpleExample.fmu`

![image](https://github.com/user-attachments/assets/5c1d09bc-505c-40de-a574-9fcc430dced2)

Resulting log.txt file with the running of the
`fmusim.exe --log-fmi-calls --logging-on --log-level warning --fmi-log-file log.txt SimpleExample.fmu`

![image](https://github.com/user-attachments/assets/7d2e475f-8d9e-416b-8f13-b1fa42327e3e)


Please note that in all 3 cases the warning
`[Warning] Debug hook active. Please attach your debugger!`
was always sent via the callbackfunctions logger

**Comment by t-sommer** [comment]
`--log-level` applies only to the messages issued by the FMU.

**Comment by stanislav-git84** [comment]
What we wish for, and find really useful, is the possibility to re-direct the two "types" of information (aka. output that is per default being printed in the terminal) to two individual files. This was possible in [FMI Compliance Checker](https://github.com/modelica-tools/FMUComplianceChecker) by calling:
`-e errors_warnings.txt -o results.csv`
The newly added --log-level option is intendent of this output redirection; it shall apply to what is being printed no matter whether this is printed in the terminal or stored in a file.
Hope this makes our request somewhat clearer.

**Comment by t-sommer** [comment]
Why don't you just pipe the output to a file?

```
fmusim --output-file MyModel_out.csv MyModel.fmu > MyModel_log.txt
```

That way you also catch messages that are printed directly to the console bypassing the FMI API.

**Comment by stanislav-git84** [comment]
Yes, this works but the separation is very much preferred option.
Rason being that by `-e errors_warnings.txt -o results.csv` we can check for any errors and warnings in the txt file (the same can be done in piped MyModel_log.txt indeed) separately from checking the actual simulation results stored in csv file. csv format is much better suited for checking values over time.

**Comment by stanislav-git84** [comment]
Hello @t-sommer would you please consider our proposed feature for implementation?
For details, please see my previous comment: https://github.com/modelica/Reference-FMUs/issues/563#issuecomment-2306999646
