### ISSUE TITLE
fmu type

### ISSUE THREAD

**Issue by YanceyYq** [modelica/Reference-FMUs#573]
After I build it, all FMU files are ModelExchange. Is there a collaborative simulation type FMU file?

**Comment by YanceyYq** [comment]
```
select the you want to build and optionally the (only for FMI 1.0)FMI_VERSIONFMI_TYPE.
```
Is FMI2.0 still not available for selection?

**Comment by t-sommer** [comment]
If you set `FMI_VERSION=2` or `FMI_VERSION=3` the FMUs will be both Co-Simulation and Model Exchange.
