### ISSUE TITLE
Wrong behaviour before first doStep

### ISSUE THREAD

**Issue by MarcoFilimonE** [modelica/Reference-FMUs#593]
FMI version: 3.0
fmusim version: 0.0.34

I have a FMU with one input and one output. The problem observed is that before the first doStep, I was expecting to see only one command for getting the output and one for setting the input (this is at least what I saw with the previous versions of fmusim), but as we can see in the below screenshot, 2 extra GET commands are being called. Is this the expected behaviour?

![image](https://github.com/user-attachments/assets/0bccfa30-f07f-4ddd-a2d9-49ef9357debb)

fmusim version 0.0.32 behaviour for the same FMU
![image](https://github.com/user-attachments/assets/243cc04e-244d-4721-acef-786e7a3c487e)

FMU + input.csv:
[SimpleExample.zip](https://github.com/user-attachments/files/17131534/SimpleExample.zip)
[input.csv](https://github.com/user-attachments/files/17131535/input.csv)

Simply run the FMU with --input-file input.csv to observe the problem.

**Comment by t-sommer** [comment]
It's sampling the initial values. What's exactly wrong with the call sequence?

**Comment by MarcoFilimonE** [comment]
Isn't fmi3GetX meant for only outputs? Or that's how it was until version 0.0.34
We can see in the first screenshot that the GET command is being called for the simulation starting point, and then for both input AND output. Only the 3rd GET is for the output, followed by a SET for the input.
![image](https://github.com/user-attachments/assets/1a6d57ca-34b3-4e6b-a9a7-71369fc5128e)

If this is the intended behaviour, then you can close this issue. I only opened it because this is not what I saw in the previous versions of FMUSIM

**Comment by t-sommer** [comment]
The reason for getting _all_ variables after initialization is to have them available for plotting in the FMUSIM GUI, so we don't have to get variables that don't change during simulation in every step. For the command line version we could skip this step. Please open a new issue if this is a requirement for you.
