### ISSUE TITLE
Wrong ouput.csv when using boolean FMI 2.0

### ISSUE THREAD

**Issue by MarcoFilimonE** [modelica/Reference-FMUs#610]
Running the attached FMU with the following command

fmusim.exe --log-fmi-calls --fmi-log-file log.txt --stop-time 0.02 --output-interval 0.01 --input-file input.csv --output-file output.csv SimpleExample.fmu

The output port (out_in_id_2d_bool*) has correct values in logging (log.txt) but wrong values in output.csv
out_in_id_2d_bool* is assigned the input port (in_id_2d_bool_alias*) which is stimulated using input.csv

[SimpleExample.zip](https://github.com/user-attachments/files/17362690/SimpleExample.zip)
[input.csv](https://github.com/user-attachments/files/17362691/input.csv)

**Comment by MarcoFilimonE** [comment]
![image](https://github.com/user-attachments/assets/d347fa31-682d-4496-a1ec-4161fc623944)

vs

![image](https://github.com/user-attachments/assets/a6a525ed-69b7-4c26-bc4f-c5dad4a683bd)

**Comment by t-sommer** [comment]
@MarcoFilimonE, do you need a release for this fix?

**Comment by MarcoFilimonE** [comment]
Yes

**Comment by MarcoFilimonE** [comment]
Thanks @t-sommer !
