### ISSUE TITLE
Create the Reference FMUs used to introduce synchronous clocks.

### ISSUE THREAD

**Issue by clagms** [modelica/Reference-FMUs#82]
As suggested by @andreas-junghanns  in https://github.com/modelica/fmi-standard/pull/1143#pullrequestreview-478153037 , we should validate the example used to introduce synchronous clocks (see https://github.com/modelica/fmi-standard/issues/1073) by creating those FMUs in the Reference FMUs.

**Comment by t-sommer** [comment]
The synchronous clock example FMUs have moved to https://github.com/clagms/synchronous-clock-fmus.
