### ISSUE TITLE
error instatiating BouncingBall in FMPy with alpha6 new headers and FMI3.xml 

### ISSUE THREAD

**Issue by iscopa** [modelica/Reference-FMUs#87]
- I could create a new BouncingBall FMU just replacing in Visual Studio its FMI3.xml: 
                      (https://github.com/modelica/Reference-FMUs/blob/master/BouncingBall/FMI3.xml)
         and its alpha6 headers:
                      (https://github.com/modelica/fmi-standard/tree/master/headers ).

- Installed FMPy developer version 7cd84fd
https://dev.azure.com/CATIA-Systems/FMPy/_build/results?buildId=806&view=results 

- FMU can be validated but not initialized. Could not debug it with new "restype" functionality in
https://github.com/CATIA-Systems/FMPy/blob/216bd08c76c05a97d145e29f8ada7a156df0bceb/fmpy/fmi3.py#L307

Could you please provide an example on its usage?

Thank you

**Comment by t-sommer** [comment]
All FMUs have been successfully built and simulated in the [latest build](https://dev.azure.com/CATIA-Systems/Reference-FMUs/_build/results?buildId=808&view=ms.vss-test-web.build-test-results-tab).
See the [CI config](https://github.com/modelica/Reference-FMUs/blob/master/azure-pipelines.yml) for the respective toolchain and FMPy version.
