### ISSUE TITLE
Rename all.c to <model_name>.c to avoid name clashes

### ISSUE THREAD

**Issue by t-sommer** [modelica/Reference-FMUs#90]
when importing and compiling multiple source code FMUs.

**Comment by clagms** [comment]
I think this is crucial to enable static linking of FMUs (the functions in `src/cosimulation.c` will all be overriden when an executable is produced by linking static libraries of different FMUs. This has never been caught by static co-sim example because we've used two instances of the same FMU.

**Comment by t-sommer** [comment]
The importers can deal with this by renaming the file (which they will have to do anyways for legacy FMUs), so I think it's not too big of a problem. The name of the file has no influence on the prefix of the symbols when linking statically.

**Comment by clagms** [comment]
Ahh I see. I misunderstood the problem. I meant that many functions (regardless of their filenames) that are shared among the reference FMUs clash when doing static linking.

**Comment by t-sommer** [comment]
This problem can only be solved by putting the functions in separate compilation units and defining them as `static`. The names of the compilation units can be changed by the importer if necessary.

**Comment by clagms** [comment]
Hmmm, I used a maybe more naive approach: prefix every common function, similar to the fmi3 functions. It's dirty, but allowed me to progress with the example...

**Comment by t-sommer** [comment]
This approach is impractical if your FMU contains external code, e.g. CVode.

**Comment by t-sommer** [comment]
See also https://github.com/modelica/Reference-FMUs/issues/215#issuecomment-1086231608.
